permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo clippy -- --deny warnings
  fmt:
    name: Format Rust code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}     # Esto asegura que hacemos checkout de la rama del PR
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Format with rustfmt
        run: cargo fmt --all

      - name: Check for modified files
        id: git-check
        run: |
          if git diff --quiet; then
            echo "modified=false" >> $GITHUB_OUTPUT
          else
            echo "modified=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git add .
          git commit -m "style: format rust code with rustfmt"
          git push
