on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo clippy -- --deny warnings
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run cargo fmt
        run: cargo fmt --all --check
