name: Rust Format
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  format:
    name: Format Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Format code
        run: |
          # Intentar formatear el código
          cargo fmt
          
          # Verificar si hay cambios
          if [[ -n $(git status --porcelain) ]]; then
            # Configurar Git
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            
            # Commit y push de los cambios
            git add .
            git commit -m "📝 Apply rustfmt changes"
            git push
          else
            echo "No formatting changes needed"
          fi
